#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8003

spring:
  profiles: dev # 开发环境
  application:
    name: microservice-consumer #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

# 客户端熔断
#feign:
#  hystrix:
#    enabled: true
---
server:
  port: 8003

spring:
  profiles: prod # 生产环境
  application:
    name: microservice-consumer #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

# 客户端熔断
#feign:
#  hystrix:
#    enabled: true
